package com.example.sams.audit.domain;

public enum AuditActionType {
    USER_CREATED,
    ENROLLMENT_ENROLLED,
    ENROLLMENT_DROPPED,
    EXAM_PUBLISHED,
    ATTENDANCE_SESSION_CREATED,
    ATTENDANCE_SESSION_UPDATED,
    SEMESTER_FEE_GENERATED,
    PAYMENT_RECORDED,
    ANNOUNCEMENT_PUBLISHED
}
